module.exports = {
  plugins: ['gatsby-plugin-sass'],
  siteMetadata: {
    characters: [
      "Bayonetta",
      "Bowser",
      "Bowser Jr.",
      "Captain Falcon",
      "Charizard",
      "Cloud",
      "Corrin",
      "Dark Pit",
      "Diddy Kong",
      "Donkey Kong",
      "Dr. Mario",
      "Duck Hunt",
      "Falco",
      "Fox",
      "Ganondorf",
      "Greninja",
      "Ike",
      "Jigglypuff",
      "King Dedede",
      "Kirby",
      "Link",
      "Little Mac",
      "Lucario",
      "Lucas",
      "Lucina",
      "Luigi",
      "Mario",
      "Marth",
      "Mega Man",
      "Meta Knight",
      "Mewtwo",
      "Mr. Game & Watch",
      "Ness",
      "Olimar",
      "Pac-Man",
      "Palutena",
      "Peach",
      "Pikachu",
      "Pit",
      "R.O.B.",
      "Robin",
      "Rosalina",
      "Roy",
      "Ryu",
      "Samus",
      "Sheik",
      "Shulk",
      "Sonic",
      "Toon Link",
      "Villager",
      "Wario",
      "Wii Fit Trainer",
      "Yoshi",
      "Zelda",
      "Zero Suit Samus"
    ]
  }
};
